create table if not exists users
(
    id       bigint generated by default as identity
    primary key,
    login    varchar(128)
    constraint uk_ow0gan20590jrb00upg3va2fn
    unique,
    password varchar(128)
);


create table if not exists animals
(
    id            bigint generated by default as identity
    primary key,
    date_of_birth date not null,
    gender        varchar(255),
    name          varchar(128)
    constraint uk_7gbiyo8u2fkxeqlnephydvgrb
    unique,
    user_id       bigint
    constraint fkmxrm8l58qpi6tx7f9simdu9f
    references users
);



